global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "prometheus_alerts.yml"

scrape_configs:
  - job_name: "titan_backend"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["backend:8000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "titan_backend_prod"

  - job_name: "titan_health_checks"
    metrics_path: "/health"
    scrape_interval: 10s
    static_configs:
      - targets: ["backend:8000"]

  - job_name: "titan_readiness_checks"
    metrics_path: "/ready"
    scrape_interval: 10s
    static_configs:
      - targets: ["backend:8000"]

  - job_name: "titan_nginx"
    metrics_path: "/stub_status"
    static_configs:
      - targets: ["nginx:80"]
