name: quizforge_upsc

description: A new Flutter project.

publish_to: 'none'

version: 1.6.0+7

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Existing packages
  file_picker: ^10.2.0
  path: ^1.9.0
  syncfusion_flutter_pdf: ^30.1.40
  http: ^1.5.0
  flutter_dotenv: ^5.2.1

  # Local database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Generate unique fingerprint for PDFs
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env