[pytest]
minversion = 7.0
addopts = -ra -q --import-mode=importlib
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
pythonpath = . app .venv/Lib/site-packages
