import 'package:titan_ai/titan_ai.dart';
import 'package:titan_knowledge_graph/titan_knowledge_graph.dart';
import 'package:titan_search/titan_search.dart';
import '../models/knowledge_object.dart';
import 'engines/ai_tutor_context_engine.dart';
import 'engines/flashcard_engine.dart';
import 'engines/knowledge_quality_engine.dart';
import 'engines/mind_map_engine.dart';
import 'engines/objectives_engine.dart';
import 'engines/question_engine.dart';
import 'engines/revision_engine.dart';
import 'engines/summary_engine.dart';
import 'models/generated_learning_assets.dart';
import 'repository/generated_assets_repository.dart';

/// Pure Dart Master Intelligence & Content Generation Engine (TITAN-K3).
class KnowledgeIntelligenceEngine {
  final SummaryEngine summaryEngine;
  final QuestionEngine questionEngine;
  final FlashcardEngine flashcardEngine;
  final RevisionEngine revisionEngine;
  final MindMapEngine mindMapEngine;
  final ObjectivesEngine objectivesEngine;
  final AITutorContextEngine tutorContextEngine;
  final KnowledgeQualityEngine qualityEngine;
  final GeneratedAssetsRepository assetsRepository;
  final SearchRepository searchRepository;
  final KnowledgeGraphRepository graphRepository;

  KnowledgeIntelligenceEngine({
    SummaryEngine? summaryEngine,
    QuestionEngine? questionEngine,
    FlashcardEngine? flashcardEngine,
    RevisionEngine? revisionEngine,
    MindMapEngine? mindMapEngine,
    ObjectivesEngine? objectivesEngine,
    AITutorContextEngine? tutorContextEngine,
    KnowledgeQualityEngine? qualityEngine,
    required this.assetsRepository,
    required this.searchRepository,
    required this.graphRepository,
    AIService? aiService,
  })  : summaryEngine = summaryEngine ?? SummaryEngine(aiService: aiService),
        questionEngine = questionEngine ?? QuestionEngine(aiService: aiService),
        flashcardEngine = flashcardEngine ?? FlashcardEngine(),
        revisionEngine = revisionEngine ?? RevisionEngine(),
        mindMapEngine = mindMapEngine ?? MindMapEngine(),
        objectivesEngine = objectivesEngine ?? ObjectivesEngine(),
        tutorContextEngine = tutorContextEngine ?? AITutorContextEngine(),
        qualityEngine = qualityEngine ?? KnowledgeQualityEngine();

  /// Processes a canonical [KnowledgeObject] to synthesize complete educational learning assets.
  /// Throws [ArgumentError] if input is invalid or raw file data.
  Future<GeneratedKnowledgeAssets> process(Object input) async {
    if (input is! KnowledgeObject) {
      throw ArgumentError(
        'TITAN-K3 Error: KnowledgeIntelligenceEngine consumes ONLY Canonical KnowledgeObject instances generated by K2. Raw PDFs, DOCX, or books are prohibited.',
      );
    }

    final obj = input;
    final stopwatch = Stopwatch()..start();

    // 1. Synthesize Summaries
    final summaries = await summaryEngine.generate(obj);

    // 2. Synthesize Questions (8 types x 3 difficulties)
    final questions = await questionEngine.generate(obj);

    // 3. Synthesize Flashcards
    final flashcards = flashcardEngine.generate(obj);

    // 4. Synthesize Revision Notes
    final revisionNotes = revisionEngine.generate(obj);

    // 5. Synthesize Mind Map Graph
    final mindMap = mindMapEngine.generate(obj);

    // 6. Synthesize Learning Objectives & Bloom's Taxonomy
    final objectivesMetadata = objectivesEngine.generate(obj);

    // 7. Synthesize AI Tutor Context
    final tutorContext = tutorContextEngine.generate(obj);

    // 8. Evaluate Quality Report & Quality Score
    final qualityReport = qualityEngine.evaluate(
      obj: obj,
      questions: questions,
      flashcards: flashcards,
      summary: summaries,
    );

    stopwatch.stop();

    final generatedAssetId = 'assets_${obj.id}';
    final generatedAssets = GeneratedKnowledgeAssets(
      id: generatedAssetId,
      sourceKnowledgeObjectId: obj.id,
      lessonTitle: obj.title,
      summaries: summaries,
      questions: questions,
      flashcards: flashcards,
      revisionNotes: revisionNotes,
      mindMap: mindMap,
      objectivesMetadata: objectivesMetadata,
      tutorContext: tutorContext,
      qualityReport: qualityReport,
      generationMetadata: {
        'generationTimeMs': stopwatch.elapsedMilliseconds,
        'questionCount': questions.length,
        'flashcardCount': flashcards.length,
        'sourceDocument': obj.source,
      },
    );

    // 9. Persist Generated Assets
    await assetsRepository.saveGeneratedAssets(generatedAssets);

    // 10. Automatically Index Generated Assets into titan_search
    await _indexGeneratedAssetsInSearch(generatedAssets);

    // 11. Expand titan_knowledge_graph
    await _expandKnowledgeGraph(generatedAssets);

    return generatedAssets;
  }

  /// Indexes generated lessons, flashcards, questions, summaries, revision notes into titan_search.
  Future<void> _indexGeneratedAssetsInSearch(
      GeneratedKnowledgeAssets assets) async {
    // Index Lesson Summary
    await searchRepository.indexItem(SearchIndexItem(
      id: 'idx_sum_${assets.id}',
      contentId: assets.sourceKnowledgeObjectId,
      title: 'Summary: ${assets.lessonTitle}',
      content: assets.summaries.summary5m,
      scope: SearchScope.revision,
      tags: ['Summary', assets.lessonTitle],
    ));

    // Index Revision Notes
    await searchRepository.indexItem(SearchIndexItem(
      id: 'idx_rev_${assets.id}',
      contentId: assets.sourceKnowledgeObjectId,
      title: 'Revision Notes: ${assets.lessonTitle}',
      content: assets.revisionNotes.onePageNotes,
      scope: SearchScope.revision,
      tags: ['Revision', assets.lessonTitle],
    ));

    // Index Questions
    for (final q in assets.questions) {
      await searchRepository.indexItem(SearchIndexItem(
        id: 'idx_${q.id}',
        contentId: assets.sourceKnowledgeObjectId,
        title: 'Question: ${q.stem}',
        content: '${q.stem} ${q.solutionExplanation}',
        scope: SearchScope.pyqs,
        tags: [q.type.name, q.difficulty],
      ));
    }
  }

  /// Expands titan_knowledge_graph with question nodes, flashcard nodes, summary nodes, and dependencies.
  Future<void> _expandKnowledgeGraph(GeneratedKnowledgeAssets assets) async {
    final rootNodeId = 'node_lesson_${assets.sourceKnowledgeObjectId}';

    // 1. Add Summary Node
    final summaryNode = KnowledgeNode(
      id: 'node_sum_${assets.id}',
      title: 'Summary: ${assets.lessonTitle}',
      type: KnowledgeNodeType.revisionItem,
      masteryWeight: 0.9,
    );
    await graphRepository.addNode(summaryNode);
    await graphRepository.addEdge(KnowledgeEdge(
      id: 'edge_sum_${assets.id}',
      sourceId: rootNodeId,
      targetId: summaryNode.id,
      relationType: KnowledgeRelationType.contains,
      weight: 1.0,
    ));

    // 2. Add Question Nodes
    for (final q in assets.questions) {
      final qNode = KnowledgeNode(
        id: 'node_q_${q.id}',
        title: 'Question: ${q.stem}',
        type: KnowledgeNodeType.pyq,
        masteryWeight: 0.7,
      );
      await graphRepository.addNode(qNode);
      await graphRepository.addEdge(KnowledgeEdge(
        id: 'edge_q_${q.id}',
        sourceId: rootNodeId,
        targetId: qNode.id,
        relationType: KnowledgeRelationType.assesses,
        weight: 0.8,
      ));
    }
  }

  /// Batch Streaming Generator for multiple KnowledgeObjects.
  Stream<GeneratedKnowledgeAssets> processBatch(
      List<KnowledgeObject> objects) async* {
    for (final obj in objects) {
      final assets = await process(obj);
      yield assets;
    }
  }
}
