import 'dart:collection';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/services.dart' show rootBundle;

import '../domain/entities/dictionary_entry.dart';
import 'dictionary_data_source.dart';

/// Bundled offline dictionary built from WordNet Release 3.0.
///
/// The dataset ships as Flutter assets generated by
/// `project_titan/tools/build_wordnet_dictionary.py`:
///
/// * `manifest.json` — source metadata, license and attribution;
/// * `headwords.json.gz` — sorted headword index for existence checks and
///   prefix suggestions;
/// * `shards/<key>.json.gz` — entries grouped by two-letter shard key,
///   loaded lazily and cached with an LRU policy so the whole dictionary
///   never sits in memory.
///
/// WordNet 3.0 is provided by Princeton University under a license that
/// permits use, copying, modification and distribution for any purpose and
/// without fee, provided the copyright notice appears on all copies.
class BundledDictionaryDataSource implements DictionaryDataSource {
  BundledDictionaryDataSource({
    Future<Uint8List> Function(String assetPath)? assetLoader,
    this.assetRoot = 'assets/dictionary',
    this.maxCachedShards = 12,
  }) : _assetLoader = assetLoader ?? _defaultAssetLoader;

  /// Source identifier used in cached entries and diagnostics.
  static const String id = 'wordnet-3.0';

  /// Root folder of the dictionary assets.
  final String assetRoot;

  /// Maximum number of decoded shards kept in the LRU cache.
  final int maxCachedShards;

  final Future<Uint8List> Function(String assetPath) _assetLoader;

  Map<String, Object?>? _manifest;
  List<String>? _headwords;
  Future<List<String>>? _headwordsLoad;
  final LinkedHashMap<String, Future<Map<String, Object?>>> _shardLoads =
      LinkedHashMap<String, Future<Map<String, Object?>>>();

  static Future<Uint8List> _defaultAssetLoader(String assetPath) async {
    final data = await rootBundle.load(assetPath);
    return data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
  }

  @override
  String get sourceId => id;

  @override
  String get attribution =>
      'WordNet\u00ae 3.0, Copyright 2006 by Princeton University. '
      'All rights reserved.';

  @override
  int? get wordCount => _manifest?['wordCount'] as int?;

  Future<Map<String, Object?>> _loadManifest() async {
    final cached = _manifest;
    if (cached != null) return cached;
    final bytes = await _assetLoader('$assetRoot/manifest.json');
    final decoded = jsonDecode(utf8.decode(bytes));
    if (decoded is! Map<String, Object?>) {
      throw const FormatException('Dictionary manifest is malformed.');
    }
    _manifest = decoded;
    return decoded;
  }

  Future<List<String>> _loadHeadwords() {
    final cached = _headwords;
    if (cached != null) return Future.value(cached);
    final inflight = _headwordsLoad;
    if (inflight != null) return inflight;
    final load = _loadHeadwordsUncached();
    _headwordsLoad = load;
    return load;
  }

  /// Loads the sorted headword index.
  ///
  /// Phase 4 spelling reuses this index so no second word list ships with
  /// the app. The list is cached after the first load.
  Future<List<String>> loadHeadwords() => _loadHeadwords();

  Future<List<String>> _loadHeadwordsUncached() async {
    // Load manifest alongside so wordCount/license metadata are ready
    // after the first index access.
    await _loadManifest();
    final bytes = await _assetLoader('$assetRoot/headwords.json.gz');
    final decoded = jsonDecode(utf8.decode(gzip.decode(bytes)));
    if (decoded is! List) {
      throw const FormatException('Dictionary headword index is malformed.');
    }
    final headwords = List<String>.unmodifiable(decoded.whereType<String>());
    _headwords = headwords;
    return headwords;
  }

  /// Two-letter shard key; must match the build script.
  static String shardKeyFor(String normalizedWord) {
    if (normalizedWord.length >= 2 &&
        _isAlpha(normalizedWord.codeUnitAt(0)) &&
        _isAlpha(normalizedWord.codeUnitAt(1))) {
      return normalizedWord.substring(0, 2);
    }
    return '_${normalizedWord.isEmpty ? '_' : normalizedWord[0]}';
  }

  static bool _isAlpha(int codeUnit) =>
      (codeUnit >= 0x61 && codeUnit <= 0x7A) ||
      (codeUnit >= 0x41 && codeUnit <= 0x5A);

  Future<Map<String, Object?>> _loadShard(String key) {
    final inflight = _shardLoads[key];
    if (inflight != null) {
      // Refresh LRU position.
      _shardLoads.remove(key);
      _shardLoads[key] = inflight;
      return inflight;
    }
    final load = _loadShardUncached(key);
    _shardLoads[key] = load;
    while (_shardLoads.length > maxCachedShards) {
      _shardLoads.remove(_shardLoads.keys.first);
    }
    return load;
  }

  Future<Map<String, Object?>> _loadShardUncached(String key) async {
    final bytes = await _assetLoader('$assetRoot/shards/$key.json.gz');
    final decoded = jsonDecode(utf8.decode(gzip.decode(bytes)));
    if (decoded is! Map<String, Object?>) {
      throw FormatException('Dictionary shard "$key" is malformed.');
    }
    return decoded;
  }

  @override
  Future<DictionaryEntry?> lookup(String normalizedWord) async {
    if (normalizedWord.isEmpty) return null;
    final shard = await _loadShard(shardKeyFor(normalizedWord));
    final raw = shard[normalizedWord];
    if (raw is! Map<String, Object?>) return null;
    return _decodeEntry(normalizedWord, raw);
  }

  DictionaryEntry _decodeEntry(
      String normalizedWord, Map<String, Object?> raw) {
    final senses = <DictionarySense>[];
    final rawSenses = raw['s'];
    if (rawSenses is List) {
      for (final sense in rawSenses.whereType<Map<String, Object?>>()) {
        final pos = sense['p'];
        if (pos is! String) continue;
        senses.add(DictionarySense(
          partOfSpeech: pos,
          definitions: _strings(sense['d']),
          examples: _strings(sense['e']),
          synonyms: _strings(sense['y']),
          antonyms: _strings(sense['a']),
        ));
      }
    }
    if (senses.isEmpty) {
      throw FormatException(
          'Dictionary entry for "$normalizedWord" has no senses.');
    }
    return DictionaryEntry(
      word: (raw['w'] as String?) ?? normalizedWord,
      normalizedWord: normalizedWord,
      senses: List.unmodifiable(senses),
      source: DictionarySourceInfo(id: sourceId, attribution: attribution),
    );
  }

  static List<String> _strings(Object? value) =>
      value is List ? List.unmodifiable(value.whereType<String>()) : const [];

  @override
  Future<List<String>> prefixMatches(String prefix, {int limit = 10}) async {
    if (prefix.isEmpty || limit <= 0) return const [];
    final headwords = await _loadHeadwords();
    // Binary search for the first headword >= prefix.
    var low = 0;
    var high = headwords.length;
    while (low < high) {
      final mid = (low + high) >> 1;
      if (headwords[mid].compareTo(prefix) < 0) {
        low = mid + 1;
      } else {
        high = mid;
      }
    }
    final matches = <String>[];
    for (var i = low; i < headwords.length && matches.length < limit; i++) {
      final word = headwords[i];
      if (!word.startsWith(prefix)) break;
      matches.add(word);
    }
    return matches;
  }
}
