import 'package:meta/meta.dart';
import 'enums.dart';

/// Immutable domain model representing a practice exercise generated by the AI Tutor.
@immutable
class TutorExercise {
  final String id;
  final String conceptId;
  final String title;
  final String prompt;
  final TutorQuestionType type;
  final List<String> hintIds;
  final String userSubmission;
  final TutorExerciseStatus status;
  final double score; // 0.0 to 100.0
  final String evaluationId;

  const TutorExercise({
    required this.id,
    required this.conceptId,
    required this.title,
    required this.prompt,
    this.type = TutorQuestionType.openEnded,
    this.hintIds = const [],
    this.userSubmission = '',
    this.status = TutorExerciseStatus.pending,
    this.score = 0.0,
    this.evaluationId = '',
  });

  TutorExercise copyWith({
    String? id,
    String? conceptId,
    String? title,
    String? prompt,
    TutorQuestionType? type,
    List<String>? hintIds,
    String? userSubmission,
    TutorExerciseStatus? status,
    double? score,
    String? evaluationId,
  }) {
    return TutorExercise(
      id: id ?? this.id,
      conceptId: conceptId ?? this.conceptId,
      title: title ?? this.title,
      prompt: prompt ?? this.prompt,
      type: type ?? this.type,
      hintIds: hintIds ?? this.hintIds,
      userSubmission: userSubmission ?? this.userSubmission,
      status: status ?? this.status,
      score: score ?? this.score,
      evaluationId: evaluationId ?? this.evaluationId,
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'conceptId': conceptId,
        'title': title,
        'prompt': prompt,
        'type': type.name,
        'hintIds': hintIds,
        'userSubmission': userSubmission,
        'status': status.name,
        'score': score,
        'evaluationId': evaluationId,
      };

  factory TutorExercise.fromJson(Map<String, dynamic> json) => TutorExercise(
        id: json['id'] as String,
        conceptId: json['conceptId'] as String,
        title: json['title'] as String,
        prompt: json['prompt'] as String,
        type: TutorQuestionType.values.firstWhere(
          (e) => e.name == json['type'],
          orElse: () => TutorQuestionType.openEnded,
        ),
        hintIds: (json['hintIds'] as List? ?? []).cast<String>(),
        userSubmission: json['userSubmission'] as String? ?? '',
        status: TutorExerciseStatus.values.firstWhere(
          (e) => e.name == json['status'],
          orElse: () => TutorExerciseStatus.pending,
        ),
        score: (json['score'] as num? ?? 0.0).toDouble(),
        evaluationId: json['evaluationId'] as String? ?? '',
      );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TutorExercise &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          conceptId == other.conceptId &&
          status == other.status;

  @override
  int get hashCode => Object.hash(id, conceptId, status);
}
