import 'dart:async';
import 'package:titan_quiz/titan_quiz.dart';
import '../exceptions/quiz_generation_exception.dart';
import '../models/assessment_generation_request.dart';
import '../models/assessment_generation_result.dart';
import '../models/assessment_question_type.dart';
import '../models/generated_question.dart';
import '../models/generation_statistics.dart';
import '../parsers/assessment_json_parser.dart';
import '../validators/assessment_validator.dart';
import '../validators/question_deduplicator.dart';
import 'assessment_generator.dart';

/// Test double implementing [AssessmentGenerator] with deterministic, configurable behaviors.
class FakeAssessmentGenerator implements AssessmentGenerator {
  bool shouldFail;
  bool shouldTimeout;
  Duration delay;
  String? customJson;
  List<GeneratedQuestion>? customQuestions;
  String failureMessage;

  final AssessmentJsonParser _jsonParser;
  final AssessmentValidator _validator;
  final QuestionDeduplicator _deduplicator;

  FakeAssessmentGenerator({
    this.shouldFail = false,
    this.shouldTimeout = false,
    this.delay = Duration.zero,
    this.customJson,
    this.customQuestions,
    this.failureMessage = 'Fake assessment generation failure.',
    AssessmentJsonParser jsonParser = const AssessmentJsonParser(),
    AssessmentValidator validator = const AssessmentValidator(),
    QuestionDeduplicator deduplicator = const QuestionDeduplicator(),
  })  : _jsonParser = jsonParser,
        _validator = validator,
        _deduplicator = deduplicator;

  @override
  Future<AssessmentGenerationResult> generateAssessment(
    AssessmentGenerationRequest request,
  ) async {
    if (delay > Duration.zero) {
      await Future<void>.delayed(delay);
    }

    request.cancellationToken?.throwIfCancelled();

    if (shouldTimeout) {
      throw TimeoutException('Fake assessment generator timeout.');
    }

    if (shouldFail) {
      throw PromptException(failureMessage);
    }

    final stopwatch = Stopwatch()..start();

    List<GeneratedQuestion> questions;
    String title = request.blueprint.title ?? 'Mock Smart Assessment';
    String description =
        request.blueprint.description ?? 'Generated by FakeAssessmentGenerator';

    if (customQuestions != null) {
      questions = customQuestions!;
    } else if (customJson != null) {
      final jsonMap = _jsonParser.extractJsonMap(customJson!);
      title = jsonMap['title']?.toString() ?? title;
      description = jsonMap['description']?.toString() ?? description;
      questions = _jsonParser.parseQuestions(map: jsonMap, request: request);
    } else {
      questions = _generateDefaultQuestions(request);
    }

    final deduplicated = _deduplicator.deduplicate(questions);

    _validator.validateQuestionsOrThrow(
      questions: deduplicated,
      request: request,
    );

    final finalQuestions =
        deduplicated.take(request.blueprint.targetQuestions).toList();
    final quizQuestions =
        finalQuestions.map((q) => q.toQuizQuestion()).toList();

    final quiz = Quiz(
      id: QuizUtils.generateQuizId(),
      title: title,
      description: description,
      sourceDocumentId: request.blueprint.documentId,
      difficulty: request.blueprint.difficulty,
      language: request.blueprint.language,
      category: request.blueprint.category,
      questions: quizQuestions,
      metadata: QuizMetadata(
        totalQuestions: quizQuestions.length,
        estimatedDurationMinutes: quizQuestions.length * 2,
        generatedBy: 'Fake Assessment Generator',
      ),
    );

    stopwatch.stop();

    return AssessmentGenerationResult(
      quiz: quiz,
      generatedQuestions: finalQuestions,
      statistics: GenerationStatistics(
        chunksProcessed: request.sources.length,
        questionsGenerated: quiz.questions.length,
        tokensUsed: 100,
        generationTime: stopwatch.elapsed,
      ),
      warnings: const [],
      processingTime: stopwatch.elapsed,
    );
  }

  List<GeneratedQuestion> _generateDefaultQuestions(
      AssessmentGenerationRequest request) {
    final list = <GeneratedQuestion>[];
    final defaultSource =
        request.sources.isNotEmpty ? request.sources.first : null;

    final targetCount = request.blueprint.targetQuestions;
    for (var i = 0; i < targetCount; i++) {
      final src = request.sources.isNotEmpty
          ? request.sources[i % request.sources.length]
          : defaultSource;

      list.add(
        GeneratedQuestion(
          id: 'fake_q_$i',
          questionText:
              'Question #${i + 1}: Based on ${src?.chunkId ?? "document"}, what is the primary conclusion?',
          options: [
            'Option A for question #${i + 1}',
            'Option B for question #${i + 1}',
            'Option C for question #${i + 1}',
            'Option D for question #${i + 1}',
          ],
          correctAnswers: const [0],
          explanation:
              'Detailed explanation justifying Option A based on source ${src?.chunkId}.',
          difficulty: request.blueprint.difficulty,
          topic: request.blueprint.topicHint ?? 'General Knowledge',
          metadata: QuestionGenerationMetadata(
            sourceDocumentId: request.blueprint.documentId,
            sourceChunkId: src?.chunkId ?? 'chunk_0',
            pageNumber: src?.pageNumber ?? 1,
            questionType: AssessmentQuestionType.mcq,
            confidenceScore: 1.0,
            isGroundingVerified: true,
          ),
        ),
      );
    }
    return list;
  }
}
