/// Content Origin & Safety Attribution Enum (TITAN-KO-025.0 P25).
///
/// Categorizes the provenance and epistemic status of remedial content to prevent
/// synthetic explanations or user annotations from ever masquerading as authoritative source facts.
library;

/// Epistemic origin and authority level of content within a remedial micro-lesson.
enum ContentOrigin {
  /// Verbatim or excerpted primary source material (e.g. constitutional articles,
  /// statutory provisions, landmark judicial ratios, official gazette notifications).
  sourceFact,

  /// Human-authored curriculum, textbook, or pedagogical explanation prepared by subject experts.
  pedagogicalExplanation,

  /// Algorithmic or LLM-generated synthesis, summarization, or concept explanation.
  /// Must NEVER be presented as an authoritative source text.
  aiGenerated,

  /// Annotations, notes, or explanations provided directly by the learner or an instructor.
  userProvided;

  /// Human-readable display label.
  String get displayName {
    switch (this) {
      case ContentOrigin.sourceFact:
        return 'Authoritative Source Fact';
      case ContentOrigin.pedagogicalExplanation:
        return 'Pedagogical Explanation';
      case ContentOrigin.aiGenerated:
        return 'AI-Generated Content';
      case ContentOrigin.userProvided:
        return 'User-Provided Content';
    }
  }

  /// Whether this origin represents verified authoritative source material.
  bool get isAuthoritativeSource => this == ContentOrigin.sourceFact;

  /// Whether this origin is synthetically generated by machine algorithms.
  bool get isSynthetic => this == ContentOrigin.aiGenerated;

  /// Whether this origin represents human-authored editorial explanations.
  bool get isHumanEditorial => this == ContentOrigin.pedagogicalExplanation;

  /// Parses a string name into a [ContentOrigin], defaulting to [pedagogicalExplanation].
  static ContentOrigin fromJson(String? name) {
    if (name == null) return ContentOrigin.pedagogicalExplanation;
    return ContentOrigin.values.firstWhere(
      (e) => e.name == name,
      orElse: () => ContentOrigin.pedagogicalExplanation,
    );
  }

  /// Serializes to JSON string.
  String toJson() => name;
}
