/// Categorization of recommendations generated by GARUDA Recommendation Engine (P21).
enum RecommendationType {
  /// Overdue item from P20 Spaced Repetition queue requiring immediate review.
  spacedReview,

  /// Prerequisite gap preventing advancement in higher-level learning objectives.
  prerequisiteGap,

  /// Weak domain performance requiring target practice (accuracy below threshold with >= minDomainAttempts).
  weakDomainRemediation,

  /// Next logical objective in sequence for curriculum progression.
  curriculumAdvance,

  /// High practice question density recommendation based on mapped P15 questions.
  practiceDensity;

  String get displayName => switch (this) {
        RecommendationType.spacedReview => 'Spaced Repetition Review',
        RecommendationType.prerequisiteGap => 'Prerequisite Gap Unblocker',
        RecommendationType.weakDomainRemediation => 'Weak Domain Remediation',
        RecommendationType.curriculumAdvance => 'Curriculum Sequence Advance',
        RecommendationType.practiceDensity => 'High-Yield Practice Density',
      };
}
