/// Recommendation Instance Entity (TITAN-KO-022.0 P22).
///
/// Immutable domain aggregate representing a persisted lifecycle instance of a
/// P21 [LearningRecommendation], tracking its lifecycle state, interactions,
/// provenance, and execution outcome.
library;

import 'package:meta/meta.dart';

import 'dismissal_reason.dart';
import 'learning_recommendation.dart';
import 'recommendation_lifecycle_state.dart';
import 'recommendation_type.dart';
import 'session_configuration.dart';

@immutable
class RecommendationInstance {
  /// Minimum allowed recommendation validity window duration.
  static const Duration minValidityDuration = Duration(days: 1);

  /// Maximum allowed recommendation validity window duration.
  static const Duration maxValidityDuration = Duration(days: 30);

  /// Default recommendation validity window duration (aligned with SM-2 review cycles).
  static const Duration defaultValidityDuration = Duration(days: 7);

  /// Unique identifier for this persisted recommendation lifecycle instance.
  final String instanceId;

  /// Target learner identifier.
  final String learnerId;

  /// Target P17 Learning Objective identifier.
  final String objectiveId;

  /// Reference to the originating P21 [LearningRecommendation.recommendationId].
  final String recommendationId;

  /// Recommendation strategy type classification from P21.
  final RecommendationType recommendationType;

  /// Composite priority score bounded strictly in [0.0, 1.0].
  final double priorityScore;

  /// Human-readable rationale generated by P21.
  final String rationale;

  /// Pre-configured turn-key P19 [SessionConfiguration] for practice execution.
  final SessionConfiguration suggestedConfig;

  /// Current lifecycle state of this recommendation instance.
  final RecommendationLifecycleState state;

  /// UTC timestamp when this recommendation instance was persisted / issued.
  final DateTime issuedAt;

  /// UTC timestamp of the most recent lifecycle state update.
  final DateTime updatedAt;

  /// Validity window duration for query-time expiration evaluation.
  final Duration validityDuration;

  /// Structured dismissal reason, required if [state] is [RecommendationLifecycleState.dismissed].
  final DismissalReason? dismissalReason;

  /// Immutable audit snapshot and factor evidence metadata.
  final Map<String, dynamic> metadata;

  RecommendationInstance({
    required this.instanceId,
    required this.learnerId,
    required this.objectiveId,
    required this.recommendationId,
    required this.recommendationType,
    required double priorityScore,
    required this.rationale,
    required this.suggestedConfig,
    this.state = RecommendationLifecycleState.issued,
    required DateTime issuedAt,
    DateTime? updatedAt,
    this.validityDuration = defaultValidityDuration,
    this.dismissalReason,
    Map<String, dynamic>? metadata,
  })  : priorityScore = priorityScore.clamp(0.0, 1.0),
        issuedAt = issuedAt.toUtc(),
        updatedAt = (updatedAt ?? issuedAt).toUtc(),
        metadata = Map<String, dynamic>.unmodifiable(metadata ?? const {}) {
    if (instanceId.trim().isEmpty) {
      throw ArgumentError('instanceId cannot be empty');
    }
    if (learnerId.trim().isEmpty) {
      throw ArgumentError('learnerId cannot be empty');
    }
    if (objectiveId.trim().isEmpty) {
      throw ArgumentError('objectiveId cannot be empty');
    }
    if (recommendationId.trim().isEmpty) {
      throw ArgumentError('recommendationId cannot be empty');
    }
    if (rationale.trim().isEmpty) {
      throw ArgumentError('rationale cannot be empty');
    }
    if (validityDuration < minValidityDuration ||
        validityDuration > maxValidityDuration) {
      throw ArgumentError(
        'validityDuration must be between $minValidityDuration and $maxValidityDuration (got $validityDuration)',
      );
    }
    if (state == RecommendationLifecycleState.dismissed &&
        dismissalReason == null) {
      throw ArgumentError(
        'dismissalReason cannot be null when recommendation is in dismissed state',
      );
    }
  }

  /// Factory constructor to instantiate a new [RecommendationInstance] from a P21 [LearningRecommendation].
  factory RecommendationInstance.fromRecommendation(
    LearningRecommendation recommendation, {
    required String instanceId,
    required DateTime issuedAt,
    Duration validityDuration = defaultValidityDuration,
    Map<String, dynamic>? metadata,
  }) {
    return RecommendationInstance(
      instanceId: instanceId,
      learnerId: recommendation.learnerId,
      objectiveId: recommendation.objectiveId,
      recommendationId: recommendation.recommendationId,
      recommendationType: recommendation.type,
      priorityScore: recommendation.priorityScore,
      rationale: recommendation.rationale,
      suggestedConfig: recommendation.suggestedConfig,
      state: RecommendationLifecycleState.issued,
      issuedAt: issuedAt,
      validityDuration: validityDuration,
      metadata: metadata ?? recommendation.metadata,
    );
  }

  /// Evaluates whether the recommendation validity duration has elapsed as of [asOf].
  ///
  /// Expiration is only applicable to non-terminal states.
  bool isExpired({required DateTime asOf}) {
    if (state.isTerminal) return false;
    final utcAsOf = asOf.toUtc();
    return utcAsOf.difference(issuedAt) > validityDuration;
  }

  /// Transitions this instance to [target] lifecycle state with deterministic timestamp [asOf].
  ///
  /// Throws [StateError] if the transition is invalid according to [RecommendationLifecycleState.canTransitionTo].
  RecommendationInstance transitionTo(
    RecommendationLifecycleState target, {
    required DateTime asOf,
    DismissalReason? dismissalReason,
    Map<String, dynamic>? metadata,
  }) {
    if (!state.canTransitionTo(target)) {
      throw StateError(
        'Cannot transition RecommendationInstance ($instanceId) from $state to $target',
      );
    }

    if (target == RecommendationLifecycleState.dismissed &&
        dismissalReason == null &&
        this.dismissalReason == null) {
      throw ArgumentError(
        'dismissalReason is required when transitioning RecommendationInstance to dismissed state',
      );
    }

    final mergedMetadata =
        metadata != null ? {...this.metadata, ...metadata} : this.metadata;

    return _copyWith(
      state: target,
      updatedAt: asOf.toUtc(),
      dismissalReason: dismissalReason ?? this.dismissalReason,
      metadata: mergedMetadata,
    );
  }

  /// Helper to transition to [RecommendationLifecycleState.viewed].
  RecommendationInstance markViewed({required DateTime asOf}) =>
      transitionTo(RecommendationLifecycleState.viewed, asOf: asOf);

  /// Helper to transition to [RecommendationLifecycleState.accepted].
  RecommendationInstance accept({required DateTime asOf}) =>
      transitionTo(RecommendationLifecycleState.accepted, asOf: asOf);

  /// Helper to transition to [RecommendationLifecycleState.dismissed].
  RecommendationInstance dismiss({
    required DismissalReason reason,
    required DateTime asOf,
  }) =>
      transitionTo(
        RecommendationLifecycleState.dismissed,
        asOf: asOf,
        dismissalReason: reason,
      );

  /// Helper to transition to [RecommendationLifecycleState.deferred].
  RecommendationInstance defer({required DateTime asOf}) =>
      transitionTo(RecommendationLifecycleState.deferred, asOf: asOf);

  /// Helper to transition to [RecommendationLifecycleState.started].
  RecommendationInstance start({required DateTime asOf}) =>
      transitionTo(RecommendationLifecycleState.started, asOf: asOf);

  /// Helper to transition to [RecommendationLifecycleState.completed].
  RecommendationInstance complete({required DateTime asOf}) =>
      transitionTo(RecommendationLifecycleState.completed, asOf: asOf);

  /// Helper to transition to [RecommendationLifecycleState.abandoned].
  RecommendationInstance abandon({required DateTime asOf}) =>
      transitionTo(RecommendationLifecycleState.abandoned, asOf: asOf);

  /// Helper to transition to [RecommendationLifecycleState.expired].
  RecommendationInstance expire({required DateTime asOf}) =>
      transitionTo(RecommendationLifecycleState.expired, asOf: asOf);

  /// Helper to transition to [RecommendationLifecycleState.superseded].
  RecommendationInstance supersede({required DateTime asOf}) =>
      transitionTo(RecommendationLifecycleState.superseded, asOf: asOf);

  RecommendationInstance _copyWith({
    RecommendationLifecycleState? state,
    DateTime? updatedAt,
    DismissalReason? dismissalReason,
    Map<String, dynamic>? metadata,
  }) {
    return RecommendationInstance(
      instanceId: instanceId,
      learnerId: learnerId,
      objectiveId: objectiveId,
      recommendationId: recommendationId,
      recommendationType: recommendationType,
      priorityScore: priorityScore,
      rationale: rationale,
      suggestedConfig: suggestedConfig,
      state: state ?? this.state,
      issuedAt: issuedAt,
      updatedAt: updatedAt ?? this.updatedAt,
      validityDuration: validityDuration,
      dismissalReason: dismissalReason ?? this.dismissalReason,
      metadata: metadata ?? this.metadata,
    );
  }

  Map<String, dynamic> toJson() => {
        'instanceId': instanceId,
        'learnerId': learnerId,
        'objectiveId': objectiveId,
        'recommendationId': recommendationId,
        'recommendationType': recommendationType.name,
        'priorityScore': priorityScore,
        'rationale': rationale,
        'suggestedConfig': suggestedConfig.toJson(),
        'state': state.name,
        'issuedAt': issuedAt.toIso8601String(),
        'updatedAt': updatedAt.toIso8601String(),
        'validityDurationMinutes': validityDuration.inMinutes,
        if (dismissalReason != null) 'dismissalReason': dismissalReason!.name,
        'metadata': metadata,
      };

  factory RecommendationInstance.fromJson(Map<String, dynamic> json) =>
      RecommendationInstance(
        instanceId: json['instanceId'] as String? ?? '',
        learnerId: json['learnerId'] as String? ?? '',
        objectiveId: json['objectiveId'] as String? ?? '',
        recommendationId: json['recommendationId'] as String? ?? '',
        recommendationType: RecommendationType.values.firstWhere(
          (t) => t.name == json['recommendationType'],
          orElse: () => RecommendationType.curriculumAdvance,
        ),
        priorityScore: (json['priorityScore'] as num?)?.toDouble() ?? 0.0,
        rationale: json['rationale'] as String? ?? '',
        suggestedConfig: SessionConfiguration.fromJson(
          Map<String, dynamic>.from(
            json['suggestedConfig'] as Map? ?? const {},
          ),
        ),
        state: RecommendationLifecycleState.values.firstWhere(
          (s) => s.name == json['state'],
          orElse: () => RecommendationLifecycleState.issued,
        ),
        issuedAt: DateTime.parse(json['issuedAt'] as String).toUtc(),
        updatedAt: json['updatedAt'] != null
            ? DateTime.parse(json['updatedAt'] as String).toUtc()
            : null,
        validityDuration: json['validityDurationMinutes'] != null
            ? Duration(minutes: json['validityDurationMinutes'] as int)
            : defaultValidityDuration,
        dismissalReason: json['dismissalReason'] != null
            ? DismissalReason.values.firstWhere(
                (r) => r.name == json['dismissalReason'],
                orElse: () => DismissalReason.other,
              )
            : null,
        metadata:
            Map<String, dynamic>.from(json['metadata'] as Map? ?? const {}),
      );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecommendationInstance &&
          instanceId == other.instanceId &&
          learnerId == other.learnerId &&
          objectiveId == other.objectiveId &&
          recommendationId == other.recommendationId &&
          recommendationType == other.recommendationType &&
          (priorityScore - other.priorityScore).abs() < 0.0001 &&
          rationale == other.rationale &&
          suggestedConfig == other.suggestedConfig &&
          state == other.state &&
          issuedAt == other.issuedAt &&
          updatedAt == other.updatedAt &&
          validityDuration == other.validityDuration &&
          dismissalReason == other.dismissalReason;

  @override
  int get hashCode => Object.hash(
        instanceId,
        learnerId,
        objectiveId,
        recommendationId,
        recommendationType,
        priorityScore,
        rationale,
        suggestedConfig,
        state,
        issuedAt,
        updatedAt,
        validityDuration,
        dismissalReason,
      );

  @override
  String toString() =>
      'RecommendationInstance($instanceId, rec: $recommendationId, learner: $learnerId, obj: $objectiveId, state: ${state.name}, score: ${priorityScore.toStringAsFixed(3)})';
}
